<?php
/**
 * RunStats
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Qase\APIClientV1\Model;

use \ArrayAccess;
use \Qase\APIClientV1\ObjectSerializer;

/**
 * RunStats Class Doc Comment
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class RunStats implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Run_stats';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'total' => 'int',
        'statuses' => 'array<string,int>',
        'untested' => 'int',
        'passed' => 'int',
        'failed' => 'int',
        'blocked' => 'int',
        'skipped' => 'int',
        'retest' => 'int',
        'inProgress' => 'int',
        'invalid' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'total' => null,
        'statuses' => null,
        'untested' => null,
        'passed' => null,
        'failed' => null,
        'blocked' => null,
        'skipped' => null,
        'retest' => null,
        'inProgress' => null,
        'invalid' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'total' => false,
        'statuses' => false,
        'untested' => false,
        'passed' => false,
        'failed' => false,
        'blocked' => false,
        'skipped' => false,
        'retest' => false,
        'inProgress' => false,
        'invalid' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'total' => 'total',
        'statuses' => 'statuses',
        'untested' => 'untested',
        'passed' => 'passed',
        'failed' => 'failed',
        'blocked' => 'blocked',
        'skipped' => 'skipped',
        'retest' => 'retest',
        'inProgress' => 'in_progress',
        'invalid' => 'invalid'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'total' => 'setTotal',
        'statuses' => 'setStatuses',
        'untested' => 'setUntested',
        'passed' => 'setPassed',
        'failed' => 'setFailed',
        'blocked' => 'setBlocked',
        'skipped' => 'setSkipped',
        'retest' => 'setRetest',
        'inProgress' => 'setInProgress',
        'invalid' => 'setInvalid'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'total' => 'getTotal',
        'statuses' => 'getStatuses',
        'untested' => 'getUntested',
        'passed' => 'getPassed',
        'failed' => 'getFailed',
        'blocked' => 'getBlocked',
        'skipped' => 'getSkipped',
        'retest' => 'getRetest',
        'inProgress' => 'getInProgress',
        'invalid' => 'getInvalid'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('statuses', $data ?? [], null);
        $this->setIfExists('untested', $data ?? [], null);
        $this->setIfExists('passed', $data ?? [], null);
        $this->setIfExists('failed', $data ?? [], null);
        $this->setIfExists('blocked', $data ?? [], null);
        $this->setIfExists('skipped', $data ?? [], null);
        $this->setIfExists('retest', $data ?? [], null);
        $this->setIfExists('inProgress', $data ?? [], null);
        $this->setIfExists('invalid', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets total
     *
     * @return int|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param int|null $total total
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets statuses
     *
     * @return array<string,int>|null
     */
    public function getStatuses()
    {
        return $this->container['statuses'];
    }

    /**
     * Sets statuses
     *
     * @param array<string,int>|null $statuses statuses
     *
     * @return self
     */
    public function setStatuses($statuses)
    {
        if (is_null($statuses)) {
            throw new \InvalidArgumentException('non-nullable statuses cannot be null');
        }
        $this->container['statuses'] = $statuses;

        return $this;
    }

    /**
     * Gets untested
     *
     * @return int|null
     * @deprecated
     */
    public function getUntested()
    {
        return $this->container['untested'];
    }

    /**
     * Sets untested
     *
     * @param int|null $untested untested
     *
     * @return self
     * @deprecated
     */
    public function setUntested($untested)
    {
        if (is_null($untested)) {
            throw new \InvalidArgumentException('non-nullable untested cannot be null');
        }
        $this->container['untested'] = $untested;

        return $this;
    }

    /**
     * Gets passed
     *
     * @return int|null
     * @deprecated
     */
    public function getPassed()
    {
        return $this->container['passed'];
    }

    /**
     * Sets passed
     *
     * @param int|null $passed passed
     *
     * @return self
     * @deprecated
     */
    public function setPassed($passed)
    {
        if (is_null($passed)) {
            throw new \InvalidArgumentException('non-nullable passed cannot be null');
        }
        $this->container['passed'] = $passed;

        return $this;
    }

    /**
     * Gets failed
     *
     * @return int|null
     * @deprecated
     */
    public function getFailed()
    {
        return $this->container['failed'];
    }

    /**
     * Sets failed
     *
     * @param int|null $failed failed
     *
     * @return self
     * @deprecated
     */
    public function setFailed($failed)
    {
        if (is_null($failed)) {
            throw new \InvalidArgumentException('non-nullable failed cannot be null');
        }
        $this->container['failed'] = $failed;

        return $this;
    }

    /**
     * Gets blocked
     *
     * @return int|null
     * @deprecated
     */
    public function getBlocked()
    {
        return $this->container['blocked'];
    }

    /**
     * Sets blocked
     *
     * @param int|null $blocked blocked
     *
     * @return self
     * @deprecated
     */
    public function setBlocked($blocked)
    {
        if (is_null($blocked)) {
            throw new \InvalidArgumentException('non-nullable blocked cannot be null');
        }
        $this->container['blocked'] = $blocked;

        return $this;
    }

    /**
     * Gets skipped
     *
     * @return int|null
     * @deprecated
     */
    public function getSkipped()
    {
        return $this->container['skipped'];
    }

    /**
     * Sets skipped
     *
     * @param int|null $skipped skipped
     *
     * @return self
     * @deprecated
     */
    public function setSkipped($skipped)
    {
        if (is_null($skipped)) {
            throw new \InvalidArgumentException('non-nullable skipped cannot be null');
        }
        $this->container['skipped'] = $skipped;

        return $this;
    }

    /**
     * Gets retest
     *
     * @return int|null
     * @deprecated
     */
    public function getRetest()
    {
        return $this->container['retest'];
    }

    /**
     * Sets retest
     *
     * @param int|null $retest retest
     *
     * @return self
     * @deprecated
     */
    public function setRetest($retest)
    {
        if (is_null($retest)) {
            throw new \InvalidArgumentException('non-nullable retest cannot be null');
        }
        $this->container['retest'] = $retest;

        return $this;
    }

    /**
     * Gets inProgress
     *
     * @return int|null
     * @deprecated
     */
    public function getInProgress()
    {
        return $this->container['inProgress'];
    }

    /**
     * Sets inProgress
     *
     * @param int|null $inProgress inProgress
     *
     * @return self
     * @deprecated
     */
    public function setInProgress($inProgress)
    {
        if (is_null($inProgress)) {
            throw new \InvalidArgumentException('non-nullable inProgress cannot be null');
        }
        $this->container['inProgress'] = $inProgress;

        return $this;
    }

    /**
     * Gets invalid
     *
     * @return int|null
     * @deprecated
     */
    public function getInvalid()
    {
        return $this->container['invalid'];
    }

    /**
     * Sets invalid
     *
     * @param int|null $invalid invalid
     *
     * @return self
     * @deprecated
     */
    public function setInvalid($invalid)
    {
        if (is_null($invalid)) {
            throw new \InvalidArgumentException('non-nullable invalid cannot be null');
        }
        $this->container['invalid'] = $invalid;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


