<?php
/**
 * SharedParametersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.15.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Qase\APIClientV1\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Qase\APIClientV1\ApiException;
use Qase\APIClientV1\Configuration;
use Qase\APIClientV1\FormDataProcessor;
use Qase\APIClientV1\HeaderSelector;
use Qase\APIClientV1\ObjectSerializer;

/**
 * SharedParametersApi Class Doc Comment
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SharedParametersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'createSharedParameter' => [
            'application/json',
        ],
        'deleteSharedParameter' => [
            'application/json',
        ],
        'getSharedParameter' => [
            'application/json',
        ],
        'getSharedParameters' => [
            'application/json',
        ],
        'updateSharedParameter' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createSharedParameter
     *
     * Create a new shared parameter
     *
     * @param  \Qase\APIClientV1\Model\SharedParameterCreate $sharedParameterCreate sharedParameterCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Qase\APIClientV1\Model\UuidResponse
     */
    public function createSharedParameter($sharedParameterCreate, string $contentType = self::contentTypes['createSharedParameter'][0])
    {
        list($response) = $this->createSharedParameterWithHttpInfo($sharedParameterCreate, $contentType);
        return $response;
    }

    /**
     * Operation createSharedParameterWithHttpInfo
     *
     * Create a new shared parameter
     *
     * @param  \Qase\APIClientV1\Model\SharedParameterCreate $sharedParameterCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Qase\APIClientV1\Model\UuidResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createSharedParameterWithHttpInfo($sharedParameterCreate, string $contentType = self::contentTypes['createSharedParameter'][0])
    {
        $request = $this->createSharedParameterRequest($sharedParameterCreate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Qase\APIClientV1\Model\UuidResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Qase\APIClientV1\Model\UuidResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\APIClientV1\Model\UuidResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation createSharedParameterAsync
     *
     * Create a new shared parameter
     *
     * @param  \Qase\APIClientV1\Model\SharedParameterCreate $sharedParameterCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSharedParameterAsync($sharedParameterCreate, string $contentType = self::contentTypes['createSharedParameter'][0])
    {
        return $this->createSharedParameterAsyncWithHttpInfo($sharedParameterCreate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createSharedParameterAsyncWithHttpInfo
     *
     * Create a new shared parameter
     *
     * @param  \Qase\APIClientV1\Model\SharedParameterCreate $sharedParameterCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createSharedParameterAsyncWithHttpInfo($sharedParameterCreate, string $contentType = self::contentTypes['createSharedParameter'][0])
    {
        $returnType = '\Qase\APIClientV1\Model\UuidResponse';
        $request = $this->createSharedParameterRequest($sharedParameterCreate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createSharedParameter'
     *
     * @param  \Qase\APIClientV1\Model\SharedParameterCreate $sharedParameterCreate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['createSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createSharedParameterRequest($sharedParameterCreate, string $contentType = self::contentTypes['createSharedParameter'][0])
    {

        // verify the required parameter 'sharedParameterCreate' is set
        if ($sharedParameterCreate === null || (is_array($sharedParameterCreate) && count($sharedParameterCreate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sharedParameterCreate when calling createSharedParameter'
            );
        }


        $resourcePath = '/shared_parameter';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sharedParameterCreate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sharedParameterCreate));
            } else {
                $httpBody = $sharedParameterCreate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation deleteSharedParameter
     *
     * Delete shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Qase\APIClientV1\Model\UuidResponse1
     */
    public function deleteSharedParameter($id, string $contentType = self::contentTypes['deleteSharedParameter'][0])
    {
        list($response) = $this->deleteSharedParameterWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation deleteSharedParameterWithHttpInfo
     *
     * Delete shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Qase\APIClientV1\Model\UuidResponse1, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteSharedParameterWithHttpInfo($id, string $contentType = self::contentTypes['deleteSharedParameter'][0])
    {
        $request = $this->deleteSharedParameterRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Qase\APIClientV1\Model\UuidResponse1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Qase\APIClientV1\Model\UuidResponse1',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\APIClientV1\Model\UuidResponse1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation deleteSharedParameterAsync
     *
     * Delete shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSharedParameterAsync($id, string $contentType = self::contentTypes['deleteSharedParameter'][0])
    {
        return $this->deleteSharedParameterAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteSharedParameterAsyncWithHttpInfo
     *
     * Delete shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteSharedParameterAsyncWithHttpInfo($id, string $contentType = self::contentTypes['deleteSharedParameter'][0])
    {
        $returnType = '\Qase\APIClientV1\Model\UuidResponse1';
        $request = $this->deleteSharedParameterRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteSharedParameter'
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deleteSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteSharedParameterRequest($id, string $contentType = self::contentTypes['deleteSharedParameter'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling deleteSharedParameter'
            );
        }


        $resourcePath = '/shared_parameter/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSharedParameter
     *
     * Get a specific shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Qase\APIClientV1\Model\SharedParameterResponse
     */
    public function getSharedParameter($id, string $contentType = self::contentTypes['getSharedParameter'][0])
    {
        list($response) = $this->getSharedParameterWithHttpInfo($id, $contentType);
        return $response;
    }

    /**
     * Operation getSharedParameterWithHttpInfo
     *
     * Get a specific shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Qase\APIClientV1\Model\SharedParameterResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedParameterWithHttpInfo($id, string $contentType = self::contentTypes['getSharedParameter'][0])
    {
        $request = $this->getSharedParameterRequest($id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Qase\APIClientV1\Model\SharedParameterResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Qase\APIClientV1\Model\SharedParameterResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\APIClientV1\Model\SharedParameterResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getSharedParameterAsync
     *
     * Get a specific shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedParameterAsync($id, string $contentType = self::contentTypes['getSharedParameter'][0])
    {
        return $this->getSharedParameterAsyncWithHttpInfo($id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSharedParameterAsyncWithHttpInfo
     *
     * Get a specific shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedParameterAsyncWithHttpInfo($id, string $contentType = self::contentTypes['getSharedParameter'][0])
    {
        $returnType = '\Qase\APIClientV1\Model\SharedParameterResponse';
        $request = $this->getSharedParameterRequest($id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSharedParameter'
     *
     * @param  string $id Identifier. (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSharedParameterRequest($id, string $contentType = self::contentTypes['getSharedParameter'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getSharedParameter'
            );
        }


        $resourcePath = '/shared_parameter/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getSharedParameters
     *
     * Get all shared parameters
     *
     * @param  int|null $limit A number of entities in result set. (optional, default to 10)
     * @param  int|null $offset How many entities should be skipped. (optional, default to 0)
     * @param  string|null $filtersSearch filtersSearch (optional)
     * @param  string|null $filtersType filtersType (optional)
     * @param  string[]|null $filtersProjectCodes filtersProjectCodes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameters'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Qase\APIClientV1\Model\SharedParameterListResponse
     */
    public function getSharedParameters($limit = 10, $offset = 0, $filtersSearch = null, $filtersType = null, $filtersProjectCodes = null, string $contentType = self::contentTypes['getSharedParameters'][0])
    {
        list($response) = $this->getSharedParametersWithHttpInfo($limit, $offset, $filtersSearch, $filtersType, $filtersProjectCodes, $contentType);
        return $response;
    }

    /**
     * Operation getSharedParametersWithHttpInfo
     *
     * Get all shared parameters
     *
     * @param  int|null $limit A number of entities in result set. (optional, default to 10)
     * @param  int|null $offset How many entities should be skipped. (optional, default to 0)
     * @param  string|null $filtersSearch (optional)
     * @param  string|null $filtersType (optional)
     * @param  string[]|null $filtersProjectCodes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameters'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Qase\APIClientV1\Model\SharedParameterListResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getSharedParametersWithHttpInfo($limit = 10, $offset = 0, $filtersSearch = null, $filtersType = null, $filtersProjectCodes = null, string $contentType = self::contentTypes['getSharedParameters'][0])
    {
        $request = $this->getSharedParametersRequest($limit, $offset, $filtersSearch, $filtersType, $filtersProjectCodes, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Qase\APIClientV1\Model\SharedParameterListResponse',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Qase\APIClientV1\Model\SharedParameterListResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\APIClientV1\Model\SharedParameterListResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getSharedParametersAsync
     *
     * Get all shared parameters
     *
     * @param  int|null $limit A number of entities in result set. (optional, default to 10)
     * @param  int|null $offset How many entities should be skipped. (optional, default to 0)
     * @param  string|null $filtersSearch (optional)
     * @param  string|null $filtersType (optional)
     * @param  string[]|null $filtersProjectCodes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedParametersAsync($limit = 10, $offset = 0, $filtersSearch = null, $filtersType = null, $filtersProjectCodes = null, string $contentType = self::contentTypes['getSharedParameters'][0])
    {
        return $this->getSharedParametersAsyncWithHttpInfo($limit, $offset, $filtersSearch, $filtersType, $filtersProjectCodes, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getSharedParametersAsyncWithHttpInfo
     *
     * Get all shared parameters
     *
     * @param  int|null $limit A number of entities in result set. (optional, default to 10)
     * @param  int|null $offset How many entities should be skipped. (optional, default to 0)
     * @param  string|null $filtersSearch (optional)
     * @param  string|null $filtersType (optional)
     * @param  string[]|null $filtersProjectCodes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getSharedParametersAsyncWithHttpInfo($limit = 10, $offset = 0, $filtersSearch = null, $filtersType = null, $filtersProjectCodes = null, string $contentType = self::contentTypes['getSharedParameters'][0])
    {
        $returnType = '\Qase\APIClientV1\Model\SharedParameterListResponse';
        $request = $this->getSharedParametersRequest($limit, $offset, $filtersSearch, $filtersType, $filtersProjectCodes, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getSharedParameters'
     *
     * @param  int|null $limit A number of entities in result set. (optional, default to 10)
     * @param  int|null $offset How many entities should be skipped. (optional, default to 0)
     * @param  string|null $filtersSearch (optional)
     * @param  string|null $filtersType (optional)
     * @param  string[]|null $filtersProjectCodes (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getSharedParameters'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getSharedParametersRequest($limit = 10, $offset = 0, $filtersSearch = null, $filtersType = null, $filtersProjectCodes = null, string $contentType = self::contentTypes['getSharedParameters'][0])
    {

        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SharedParametersApi.getSharedParameters, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling SharedParametersApi.getSharedParameters, must be bigger than or equal to 1.');
        }
        
        if ($offset !== null && $offset > 100000) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling SharedParametersApi.getSharedParameters, must be smaller than or equal to 100000.');
        }
        if ($offset !== null && $offset < 0) {
            throw new \InvalidArgumentException('invalid value for "$offset" when calling SharedParametersApi.getSharedParameters, must be bigger than or equal to 0.');
        }
        




        $resourcePath = '/shared_parameter';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $offset,
            'offset', // param base name
            'integer', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filtersSearch,
            'filters[search]', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filtersType,
            'filters[type]', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $filtersProjectCodes,
            'filters[project_codes][]', // param base name
            'array', // openApiType
            '', // style
            false, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation updateSharedParameter
     *
     * Update shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  \Qase\APIClientV1\Model\SharedParameterUpdate $sharedParameterUpdate sharedParameterUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Qase\APIClientV1\Model\UuidResponse1
     */
    public function updateSharedParameter($id, $sharedParameterUpdate, string $contentType = self::contentTypes['updateSharedParameter'][0])
    {
        list($response) = $this->updateSharedParameterWithHttpInfo($id, $sharedParameterUpdate, $contentType);
        return $response;
    }

    /**
     * Operation updateSharedParameterWithHttpInfo
     *
     * Update shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  \Qase\APIClientV1\Model\SharedParameterUpdate $sharedParameterUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedParameter'] to see the possible values for this operation
     *
     * @throws \Qase\APIClientV1\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Qase\APIClientV1\Model\UuidResponse1, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateSharedParameterWithHttpInfo($id, $sharedParameterUpdate, string $contentType = self::contentTypes['updateSharedParameter'][0])
    {
        $request = $this->updateSharedParameterRequest($id, $sharedParameterUpdate, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Qase\APIClientV1\Model\UuidResponse1',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\Qase\APIClientV1\Model\UuidResponse1',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Qase\APIClientV1\Model\UuidResponse1',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation updateSharedParameterAsync
     *
     * Update shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  \Qase\APIClientV1\Model\SharedParameterUpdate $sharedParameterUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSharedParameterAsync($id, $sharedParameterUpdate, string $contentType = self::contentTypes['updateSharedParameter'][0])
    {
        return $this->updateSharedParameterAsyncWithHttpInfo($id, $sharedParameterUpdate, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation updateSharedParameterAsyncWithHttpInfo
     *
     * Update shared parameter
     *
     * @param  string $id Identifier. (required)
     * @param  \Qase\APIClientV1\Model\SharedParameterUpdate $sharedParameterUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateSharedParameterAsyncWithHttpInfo($id, $sharedParameterUpdate, string $contentType = self::contentTypes['updateSharedParameter'][0])
    {
        $returnType = '\Qase\APIClientV1\Model\UuidResponse1';
        $request = $this->updateSharedParameterRequest($id, $sharedParameterUpdate, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'updateSharedParameter'
     *
     * @param  string $id Identifier. (required)
     * @param  \Qase\APIClientV1\Model\SharedParameterUpdate $sharedParameterUpdate (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['updateSharedParameter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateSharedParameterRequest($id, $sharedParameterUpdate, string $contentType = self::contentTypes['updateSharedParameter'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling updateSharedParameter'
            );
        }

        // verify the required parameter 'sharedParameterUpdate' is set
        if ($sharedParameterUpdate === null || (is_array($sharedParameterUpdate) && count($sharedParameterUpdate) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sharedParameterUpdate when calling updateSharedParameter'
            );
        }


        $resourcePath = '/shared_parameter/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sharedParameterUpdate)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sharedParameterUpdate));
            } else {
                $httpBody = $sharedParameterUpdate;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PATCH',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
