<?php
/**
 * ConfigurationsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Qase\APIClientV1\Test\Api;

use \Qase\APIClientV1\Configuration;
use \Qase\APIClientV1\ApiException;
use \Qase\APIClientV1\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ConfigurationsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ConfigurationsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createConfiguration
     *
     * Create a new configuration in a particular group..
     *
     */
    public function testCreateConfiguration()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createConfigurationGroup
     *
     * Create a new configuration group..
     *
     */
    public function testCreateConfigurationGroup()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getConfigurations
     *
     * Get all configuration groups with configurations..
     *
     */
    public function testGetConfigurations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
