<?php
/**
 * DefectsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Qase.io TestOps API v1
 *
 * Qase TestOps API v1 Specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@qase.io
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Qase\APIClientV1\Test\Api;

use \Qase\APIClientV1\Configuration;
use \Qase\APIClientV1\ApiException;
use \Qase\APIClientV1\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DefectsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Qase\APIClientV1
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DefectsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createDefect
     *
     * Create a new defect.
     *
     */
    public function testCreateDefect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteDefect
     *
     * Delete defect.
     *
     */
    public function testDeleteDefect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDefect
     *
     * Get a specific defect.
     *
     */
    public function testGetDefect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getDefects
     *
     * Get all defects.
     *
     */
    public function testGetDefects()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for resolveDefect
     *
     * Resolve a specific defect.
     *
     */
    public function testResolveDefect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDefect
     *
     * Update defect.
     *
     */
    public function testUpdateDefect()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateDefectStatus
     *
     * Update a specific defect status.
     *
     */
    public function testUpdateDefectStatus()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
